---
title: "CourseProject Codebook"
author: "MasterMezcalero"
date: "2023-02-08"
output: pdf_document
---

This document described the variables used and steps taken in creating the tidy data set.

#### Variables

Variable Name     Variable description

x_test            Data frame containing the data from x_test file
y_test            Data frame containing the data from y_test file
subject_test      Data frame containing the data from subject_test file
x_train           Data frame containing the data from x_train file
y_train           Data frame containing the data from y_train file
subject_train     Data frame containing the data from subject_train file
x                 Data set created by merging x_test and x_train
y                 Data set created by merging y_test and y_train
subject           Data set created by merging subject_test and subject_train
features          Data frame containing the data from features.txt
MeanAndStd        Contains the position of variables names that contain "Mean" or "Std" in features 
activity_labels   Data frame containing the data from activity_labels file
activity_names    Contains the data from y and a separate column with activity labels 
CleanData         Contains a clean raw data set with data from x, y and subject
Tidy              Tidy data set with the average for each variable in each column

#### Steps taken to clean the data set

1. Initialized the test and train data sets to their own data frames
2. Linked the test and train data sets
3. Saved the feature indices of the Mean and Std features to a new variable
4. Read the activity label data into a new variable and used this to name the activities in variable y
5. Used the activity names to name all columns in x, then assigned names to y and subject
6. Combined x, y and subject into a new data table
7. Applied the mean function to all fields in the table and saved in a new variable
8. Wrote the output to CSV